### PR TITLE
remove patch level version for archive-zip. [Fixes #3]

### LINKED ISSUE #3: archive-zip dependency is incompatible with chromedriver-helper
`geckodriver-helper` (0.0.4) and chromedriver-helper (1.2.0) depend on conflicting versions of `archive-zip`: versions `~> 0.7.0` and `~> 0.10`, respectively.  This prevents both from being installed together in the same repository.

```
Bundler could not find compatible versions for gem "archive-zip":
  In snapshot (Gemfile.lock):
    archive-zip (= 0.11.0)

  In Gemfile:
    chromedriver-helper (~> 1.2) was resolved to 1.2.0, which depends on
      archive-zip (~> 0.10)

    geckodriver-helper (~> 0.0.4) was resolved to 0.0.4, which depends on
      archive-zip (~> 0.7.0)
```

### PR DESCRIPTION
**Pull request by tmertens**

### CODE REVIEW

**Review by varyonic — APPROVED** [review]
Thank you.

**Comment by dmitryreznik** [comment]
Thx

**Comment by varyonic** [comment]
Awesome! @dmitryreznik  Any chance of a gem push? cucumber-rails has this gem as a dependency.

**Comment by dmitryreznik** [comment]
@varyonic I will push it tomorrow... sorry very busy right now

**Pull request merged**
